### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 0xSynapse**
Hi @jameslahm, 

Ankan here. I am a Computer Vision Engineer at OpenCV. Thanks for YOLOv10; it's really cool with its new advancements.

Recently, I wrote a detailed article on [YOLOv10](https://learnopencv.com/yolov10/) at LearnOpenCV. 

I thought maybe we could add a readme button for the blog to help the community understand it better. As I did the same for YOLOv9.

Looking forward to it.

Thank you!

### CODE REVIEW

**Comment by jameslahm** [comment]
@0xSynapse Thanks a lot! We appreciate your efforts very much and we are very pleased to highlight your blog in the README. Additionally, we found some inconsistencies with our understanding and could you please help us on these? Thank you!
1. In this [example](https://learnopencv.com/wp-content/uploads/2024/06/image32.gif) and this [example](https://learnopencv.com/wp-content/uploads/2024/06/image5-1.gif), we found that YOLOv10 fails to detect some small objects or objects in the distance, e.g., [the person in the subway](https://learnopencv.com/wp-content/uploads/2024/06/image32.gif) and [the person in the distance in the left down corner](https://learnopencv.com/wp-content/uploads/2024/06/image5-1.gif). We previously provided some clarifications and suggestions [here](https://github.com/THU-MIG/yolov10/issues/136). Could you please set a smaller confidence threshold for YOLOv10? Thanks!
2. Is the AP<sub>50</sub> a typo in this [table](https://learnopencv.com/wp-content/uploads/2024/06/image15.png)? The AP<sup>val</sup> of YOLOv10-L and YOLOv8-M is 53.2 and 50.2, respectively, rather than AP<sub>50</sub>. Thanks!
3. In this [table](https://learnopencv.com/wp-content/uploads/2024/06/image15.png), do you measure the inference speed and FPS for YOLOv10 using the pytorch model? Due to that in the non-exported format, e.g., pytorch, the speed of YOLOv10 is biased because the unnecessary `cv2` and `cv3` operations in the `v10Detect` are executed during inference, could you please set the `export` attribute of `v10Detect` to `True` before the measurement using the pytorch model like below? Thanks!
  ```python
  from ultralytics import YOLOv10
  
  model = YOLOv10('yolov10n.pt')
  model.model.model[-1].export = True
  model.model.model[-1].format = 'onnx'
  del model.model.model[-1].cv2
  del model.model.model[-1].cv3
  model.predict(...)
  ```
4. In the **YOLOv10 – Benchmarks** section, could you please also set the `export` attribute of `v10Detect` to `True` before the measurement using the pytorch model? Thanks!

Thank you very much! ❤️

**Comment by 0xSynapse** [comment]
Hi @jameslahm, thanks for the suggestions, 

2. - yes, it's a typo. It's fixed now.

1. , 3. , 4. - As this is an introduction blog, we are more focused on using the default parameters. We will write more blogs about this later when we experiment with the parmas. For now, I will add one subsection for each section, as you mentioned the issues and solutions.

Again, thanks for the suggestions.

**Comment by jameslahm** [comment]
@0xSynapse Thanks a lot! Could you please also replace the data of YOLOv9-C with its AP<sup>val</sup> in this [table](https://learnopencv.com/wp-content/uploads/2024/06/image15.png)? Thanks!

**Comment by 0xSynapse** [comment]
@jameslahm , Sorry for the typo it's fixed now.

Rest 2 issues and solutions, I will add today itself.

Thanks for the help!

**Comment by 0xSynapse** [comment]
@jameslahm updated your issues and suggestions. 

Now I think we can add it to the README.

**Comment by jameslahm** [comment]
Thank you!

**Pull request merged**
