### PR TITLE
Added video output support for gradio

### PR DESCRIPTION
**Pull request by senceryucel**
Video inputs were accepted, but only a single frame was shown as output in the Gradio interface. 

I added:
1. A flag for the input type (image/video)
2. The display of the output video when the detection is finished.

### CODE REVIEW

**Review by Saintloxx — APPROVED** [review]

**Comment by jameslahm** [comment]
Thanks very much for your contribution! But We encounter error when running the demo locally.
```
ValueError: Cannot process this value as an Image, it is of type: <class 'tuple'>
```
Could you please fix this? Thank you!

**Comment by senceryucel** [comment]
Hey @jameslahm 

I've fixed the issue by adding a new function yolov10_inference_for_examples that returns only the annotated image, which makes the output format match the expected single image output for gradio Examples.

I've committed the changes. Please let me know if there are any other issues or further improvements needed.

**Comment by jameslahm** [comment]
Thank you! We encounter another bug when uploading the video, like below
image
Could you please fix this? Thank you!

**Comment by senceryucel** [comment]
@jameslahm As far as I understood, it is because the video that you uploaded does not have browser-compatible container or codec:

image

The new commit includes a file size checker for videos. I could only reproduce the bug on my local with a video that sized 65MB. Thus, I limited the video file size to 20MB.

If this does not fix the problem for the video that you have encountered the error in the beginning with, please share the video for me to investigate further.

Thank you.

**Comment by jameslahm** [comment]
Thank you! We find the problem still exists. Our test video is below

https://github.com/THU-MIG/yolov10/assets/43805318/4d6523e5-a6b8-461a-9bc1-f51f78b7c5c5

**Comment by senceryucel** [comment]
@jameslahm Thank you. I tried to reproduce the issue, but I could not:

image

I have tried with 3 different browsers but it's clear that the browser is not the problem here. The only thing I can think of is the version mismatch between your and my environments. Thus, can you please make sure that you have a fresh environment with only the packages in the requirements.txt file are installed?
Thank you.

**Comment by jameslahm** [comment]
Thanks! We found that the reason may lie in the unsupported video format in our browser, and the container format `webm` and codec format `vp80` may be more widely supported in browsers according to https://stackoverflow.com/questions/49530857/python-opencv-video-format-play-in-browser. Would you mind replacing the container and codec formats as below? Thanks a lot!
```python
output_video_path = tempfile.mktemp(suffix=".webm")
out = cv2.VideoWriter(output_video_path, cv2.VideoWriter_fourcc(*'vp80'), fps, (frame_width, frame_height))
```
Besides, would you mind also resolving the conflict? Thank you!

**Comment by jameslahm** [comment]
Thank you!

**Pull request merged**
